all: prog72 prog71 prog71_sleepmore


prog71_sleepmore: prog71_sleepmore.c
	gcc -g prog71_sleepmore.c -o prog71_sleepmore


prog72: prog72.c
	gcc -g prog72.c -o prog72

prog71: prog71.c
	gcc -g prog71.c -o prog71

clean:
	rm prog72 prog71 prog71_sleepmore